[package]
name = "proxy-blocklist"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
proxy-base = { path = "../base" }
proxy-rrd = { path = "../rrd" }
proxy-msg = { path = "../msg" }
proxy-net = { path = "../net" }
proxy-origin = { path = "../origin" }
proxy-config = { path = "../config" }
proxy-metrics = { path = "../metrics" }
