[package]
name = "proxy-http"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
proxy-base = { path = "../base" }
proxy-sys = { path = "../sys" }
proxy-msg = { path = "../msg" }
proxy-net = { path = "../net" }
proxy-origin = { path = "../origin" }
proxy-cache = { path = "../cache" }
proxy-freshness = { path = "../freshness" }
proxy-metrics = { path = "../metrics" }
proxy-workers = { path = "../workers" }
